In [1]:
!pip install torch torchvision numpy matplotlib


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: C:\Users\devas\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip


In [2]:
import torch
print(f"PyTorch version: {torch.__version__}")
print("PyTorch installed successfully!")

PyTorch version: 2.9.1+cpu
PyTorch installed successfully!


In [3]:
import torch
import numpy as np
import matplotlib.pyplot as plt

print(f"PyTorch version: {torch.__version__}")
print(f"NumPy version: {np.__version__}")
print("All libraries imported successfully! ✓")

PyTorch version: 2.9.1+cpu
NumPy version: 2.2.6
All libraries imported successfully! ✓


In [4]:
# Task 1: Introduction to PyTorch Tensors and Basic Operations
import torch
import numpy as np

print("=" * 50)
print("TASK 1: PyTorch Tensors and Basic Operations")
print("=" * 50)

# a) Understanding PyTorch tensors, initialization methods, and data types

# Different initialization methods
print("\n1. Tensor Initialization Methods:\n")

# From Python list
tensor_from_list = torch.tensor([1, 2, 3, 4, 5])
print(f"From list: {tensor_from_list}")
print(f"Data type: {tensor_from_list.dtype}\n")

# Zeros tensor
zeros_tensor = torch.zeros(3, 4)
print(f"Zeros tensor (3x4):\n{zeros_tensor}\n")

# Ones tensor
ones_tensor = torch.ones(2, 3)
print(f"Ones tensor (2x3):\n{ones_tensor}\n")

# Random tensor
random_tensor = torch.rand(2, 3)
print(f"Random tensor (2x3):\n{random_tensor}\n")

# Range tensor
range_tensor = torch.arange(0, 10, 2)
print(f"Range tensor (0 to 10, step 2): {range_tensor}\n")

# Different data types
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)
bool_tensor = torch.tensor([True, False, True], dtype=torch.bool)

print(f"Float32 tensor: {float_tensor}, dtype: {float_tensor.dtype}")
print(f"Int64 tensor: {int_tensor}, dtype: {int_tensor.dtype}")
print(f"Bool tensor: {bool_tensor}, dtype: {bool_tensor.dtype}\n")

# b) Tensor operations: arithmetic, broadcasting, indexing, and reshaping

print("\n2. Tensor Operations:\n")

# Arithmetic operations
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

print(f"Tensor a:\n{a}\n")
print(f"Tensor b:\n{b}\n")

print(f"Addition (a + b):\n{a + b}\n")
print(f"Subtraction (a - b):\n{a - b}\n")
print(f"Element-wise multiplication (a * b):\n{a * b}\n")
print(f"Matrix multiplication (a @ b):\n{a @ b}\n")

# Broadcasting
x = torch.tensor([[1], [2], [3]])
y = torch.tensor([10, 20, 30])
print(f"Broadcasting example:\n{x} + {y} =\n{x + y}\n")

# Indexing
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Original tensor:\n{tensor}\n")
print(f"First row: {tensor[0]}\n")
print(f"Second column: {tensor[:, 1]}\n")
print(f"Element at (1,2): {tensor[1, 2]}\n")

# Reshaping
reshaped = tensor.reshape(1, 9)
print(f"Reshaped to (1, 9):\n{reshaped}\n")
print(f"View as (9, 1):\n{tensor.view(9, 1)}\n")

# c) Automatic differentiation using PyTorch's Autograd system

print("\n3. Automatic Differentiation with Autograd:\n")

# Requires gradient tracking
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)

# Define a computation
z = x**2 + 2*y + 3
print(f"z = x² + 2y + 3")
print(f"x = {x.item()}, y = {y.item()}")
print(f"z = {z.item()}\n")

# Compute gradients
z.backward()

print(f"dz/dx = {x.grad.item()} (expected: 2*x = 4)")
print(f"dz/dy = {y.grad.item()} (expected: 2)\n")

# More complex example
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x * 2
z = y.mean()

print(f"x = {x}")
print(f"y = x * 2 = {y}")
print(f"z = mean(y) = {z.item()}\n")

z.backward()
print(f"Gradients: {x.grad}\n")

TASK 1: PyTorch Tensors and Basic Operations

1. Tensor Initialization Methods:

From list: tensor([1, 2, 3, 4, 5])
Data type: torch.int64

Zeros tensor (3x4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones tensor (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random tensor (2x3):
tensor([[0.2801, 0.9474, 0.9013],
        [0.1823, 0.0438, 0.0840]])

Range tensor (0 to 10, step 2): tensor([0, 2, 4, 6, 8])

Float32 tensor: tensor([1., 2., 3.]), dtype: torch.float32
Int64 tensor: tensor([1, 2, 3]), dtype: torch.int64
Bool tensor: tensor([ True, False,  True]), dtype: torch.bool


2. Tensor Operations:

Tensor a:
tensor([[1, 2],
        [3, 4]])

Tensor b:
tensor([[5, 6],
        [7, 8]])

Addition (a + b):
tensor([[ 6,  8],
        [10, 12]])

Subtraction (a - b):
tensor([[-4, -4],
        [-4, -4]])

Element-wise multiplication (a * b):
tensor([[ 5, 12],
        [21, 32]])

Matrix multiplication (a @ b):
tensor([[19, 22],
        [43, 50]])

Br

In [5]:
# Task 2: Linear Algebra Operations with TensorFlow
import tensorflow as tf
import numpy as np

print("=" * 50)
print("TASK 2: Linear Algebra with TensorFlow")
print("=" * 50)

# Matrix operations
A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
B = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

print(f"\nMatrix A:\n{A.numpy()}\n")
print(f"Matrix B:\n{B.numpy()}\n")

# Matrix multiplication
C = tf.matmul(A, B)
print(f"Matrix Multiplication (A @ B):\n{C.numpy()}\n")

# Element-wise operations
print(f"Element-wise Addition:\n{tf.add(A, B).numpy()}\n")
print(f"Element-wise Multiplication:\n{tf.multiply(A, B).numpy()}\n")

# Transpose
print(f"Transpose of A:\n{tf.transpose(A).numpy()}\n")

# Determinant
det_A = tf.linalg.det(A)
print(f"Determinant of A: {det_A.numpy()}\n")

# Inverse
inv_A = tf.linalg.inv(A)
print(f"Inverse of A:\n{inv_A.numpy()}\n")

# Verify A * inv(A) = I
identity = tf.matmul(A, inv_A)
print(f"A * inv(A) (should be identity):\n{identity.numpy()}\n")

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = tf.linalg.eigh(A)
print(f"Eigenvalues: {eigenvalues.numpy()}")
print(f"Eigenvectors:\n{eigenvectors.numpy()}\n")

TASK 2: Linear Algebra with TensorFlow

Matrix A:
[[1. 2.]
 [3. 4.]]

Matrix B:
[[5. 6.]
 [7. 8.]]

Matrix Multiplication (A @ B):
[[19. 22.]
 [43. 50.]]

Element-wise Addition:
[[ 6.  8.]
 [10. 12.]]

Element-wise Multiplication:
[[ 5. 12.]
 [21. 32.]]

Transpose of A:
[[1. 3.]
 [2. 4.]]

Determinant of A: -2.0

Inverse of A:
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]

A * inv(A) (should be identity):
[[ 1.0000000e+00  0.0000000e+00]
 [-4.7683716e-07  1.0000002e+00]]

Eigenvalues: [-0.8541021  5.854102 ]
Eigenvectors:
[[-0.85065085 -0.5257311 ]
 [ 0.5257311  -0.85065085]]



In [6]:
# Task 3: AND/OR Gates using Perceptron
import torch
import torch.nn as nn
import numpy as np

print("=" * 50)
print("TASK 3: AND/OR Gates using Perceptron")
print("=" * 50)

# Define Perceptron class
class Perceptron(nn.Module):
    def __init__(self, input_size):
        super(Perceptron, self).__init__()
        self.linear = nn.Linear(input_size, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        return self.sigmoid(self.linear(x))

# Training function
def train_perceptron(model, X, y, epochs=1000, lr=0.1):
    criterion = nn.BCELoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=lr)
    
    for epoch in range(epochs):
        # Forward pass
        outputs = model(X)
        loss = criterion(outputs, y)
        
        # Backward pass
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if (epoch + 1) % 200 == 0:
            print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

# AND Gate
print("\n--- AND Gate ---\n")
X_and = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
y_and = torch.tensor([[0], [0], [0], [1]], dtype=torch.float32)

model_and = Perceptron(2)
train_perceptron(model_and, X_and, y_and)

print("\nAND Gate Results:")
with torch.no_grad():
    predictions = model_and(X_and)
    for i, (input_val, pred, actual) in enumerate(zip(X_and, predictions, y_and)):
        print(f"Input: {input_val.numpy()} -> Prediction: {pred.item():.4f}, Actual: {actual.item()}")

# OR Gate
print("\n--- OR Gate ---\n")
X_or = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
y_or = torch.tensor([[0], [1], [1], [1]], dtype=torch.float32)

model_or = Perceptron(2)
train_perceptron(model_or, X_or, y_or)

print("\nOR Gate Results:")
with torch.no_grad():
    predictions = model_or(X_or)
    for i, (input_val, pred, actual) in enumerate(zip(X_or, predictions, y_or)):
        print(f"Input: {input_val.numpy()} -> Prediction: {pred.item():.4f}, Actual: {actual.item()}")

TASK 3: AND/OR Gates using Perceptron

--- AND Gate ---

Epoch [200/1000], Loss: 0.3596
Epoch [400/1000], Loss: 0.2578
Epoch [600/1000], Loss: 0.2029
Epoch [800/1000], Loss: 0.1677
Epoch [1000/1000], Loss: 0.1429

AND Gate Results:
Input: [0. 0.] -> Prediction: 0.0083, Actual: 0.0
Input: [0. 1.] -> Prediction: 0.1493, Actual: 0.0
Input: [1. 0.] -> Prediction: 0.1492, Actual: 0.0
Input: [1. 1.] -> Prediction: 0.7869, Actual: 1.0

--- OR Gate ---

Epoch [200/1000], Loss: 0.2877
Epoch [400/1000], Loss: 0.1927
Epoch [600/1000], Loss: 0.1429
Epoch [800/1000], Loss: 0.1128
Epoch [1000/1000], Loss: 0.0927

OR Gate Results:
Input: [0. 0.] -> Prediction: 0.1925, Actual: 0.0
Input: [0. 1.] -> Prediction: 0.9258, Actual: 1.0
Input: [1. 0.] -> Prediction: 0.9250, Actual: 1.0
Input: [1. 1.] -> Prediction: 0.9985, Actual: 1.0


In [7]:
# Task 4: XOR Problem using PyTorch Neural Network (FIXED)
import torch
import torch.nn as nn
import torch.optim as optim

print("=" * 50)
print("TASK 4: XOR Problem with Neural Network")
print("=" * 50)

# XOR dataset
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
y = torch.tensor([[0], [1], [1], [0]], dtype=torch.float32)

# Define Neural Network with better architecture
class XORNet(nn.Module):
    def __init__(self):
        super(XORNet, self).__init__()
        # Increased hidden neurons for more robust learning
        self.hidden = nn.Linear(2, 4)  # Changed from 2 to 4
        self.output = nn.Linear(4, 1)  # Changed from 2 to 4
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        x = self.sigmoid(self.hidden(x))
        x = self.sigmoid(self.output(x))
        return x

# Initialize model
model = XORNet()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)  # Changed to Adam with lower lr

# Training
print("\nTraining XOR Network...\n")
losses = []
epochs = 5000

for epoch in range(epochs):
    # Forward pass
    outputs = model(X)
    loss = criterion(outputs, y)
    losses.append(loss.item())
    
    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if (epoch + 1) % 1000 == 0:
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

# Test the model
print("\nXOR Results:")
with torch.no_grad():
    predictions = model(X)
    for input_val, pred, actual in zip(X, predictions, y):
        result = "✓" if (pred.item() > 0.5) == (actual.item() > 0.5) else "✗"
        print(f"Input: {input_val.numpy()} -> Prediction: {pred.item():.4f}, Actual: {actual.item()} {result}")

print(f"\nFinal Loss: {loss.item():.4f}")

TASK 4: XOR Problem with Neural Network

Training XOR Network...

Epoch [1000/5000], Loss: 0.0005
Epoch [2000/5000], Loss: 0.0002
Epoch [3000/5000], Loss: 0.0001
Epoch [4000/5000], Loss: 0.0000
Epoch [5000/5000], Loss: 0.0000

XOR Results:
Input: [0. 0.] -> Prediction: 0.0000, Actual: 0.0 ✓
Input: [0. 1.] -> Prediction: 1.0000, Actual: 1.0 ✓
Input: [1. 0.] -> Prediction: 1.0000, Actual: 1.0 ✓
Input: [1. 1.] -> Prediction: 0.0000, Actual: 0.0 ✓

Final Loss: 0.0000


In [8]:
# Task 5: Simple Neural Network for Regression
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

print("=" * 50)
print("TASK 5: Neural Network for Regression")
print("=" * 50)

# Generate synthetic data for regression
np.random.seed(42)
X_train = np.linspace(-10, 10, 100).reshape(-1, 1)
y_train = 2 * X_train + 3 + np.random.randn(100, 1) * 2

X_train = torch.FloatTensor(X_train)
y_train = torch.FloatTensor(y_train)

# Define Neural Network for Regression
class RegressionNet(nn.Module):
    def __init__(self):
        super(RegressionNet, self).__init__()
        self.fc1 = nn.Linear(1, 10)
        self.fc2 = nn.Linear(10, 10)
        self.fc3 = nn.Linear(10, 1)
        self.relu = nn.ReLU()
    
    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Initialize model
model = RegressionNet()
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training
print("\nTraining Regression Model...\n")
epochs = 1000
losses = []

for epoch in range(epochs):
    # Forward pass
    outputs = model(X_train)
    loss = criterion(outputs, y_train)
    losses.append(loss.item())
    
    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if (epoch + 1) % 200 == 0:
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

# Test the model
print("\nMaking predictions...")
with torch.no_grad():
    X_test = torch.FloatTensor(np.linspace(-10, 10, 20).reshape(-1, 1))
    predictions = model(X_test)
    
    print("\nSample Predictions:")
    for i in range(0, 20, 4):
        print(f"Input: {X_test[i].item():.2f} -> Prediction: {predictions[i].item():.2f}")

print("\nModel trained successfully!")
print("You can visualize the results by plotting X_test vs predictions")

TASK 5: Neural Network for Regression

Training Regression Model...

Epoch [200/1000], Loss: 3.0828
Epoch [400/1000], Loss: 3.0385
Epoch [600/1000], Loss: 2.9976
Epoch [800/1000], Loss: 2.9617
Epoch [1000/1000], Loss: 2.9344

Making predictions...

Sample Predictions:
Input: -10.00 -> Prediction: -15.84
Input: -5.79 -> Prediction: -9.35
Input: -1.58 -> Prediction: -0.61
Input: 2.63 -> Prediction: 8.41
Input: 6.84 -> Prediction: 16.63

Model trained successfully!
You can visualize the results by plotting X_test vs predictions
